image: node:20-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out/

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main